<?php

/*
 * State constants
 */
const ST_BGA_GAME_SETUP = 1;

const ST_ASSIGN_CHARACTERS = 10;
const ST_CHARACTER_CHECK = 11;

const ST_DEAL_CARDS = 20;
const ST_ACTIVATE_BIOME = 21;

const ST_BEGIN_BUILD_PHASE = 30;
const ST_PLAYER_BUILD_STEP = 31;
const ST_CHOOSE_BUILD_ANIMAL = 32;
const ST_CHOOSE_BUILD_SECTION = 33;
const ST_END_BUILD_PHASE = 39;

const ST_PLAYER_TURN = 40;

const ST_END_GAME = 99;

?>
